apiVersion: v1
kind: Service
metadata:
  name: servicio2-service-np
  labels:
    name: servicio2-deploy
    app: servicio2-app
spec:
  type: NodePort
  selector:
    app: servicio2-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30072



    